"""Owner-provided ESF and BIO Registry portfolio descriptions."""

from system_pages import enquiry, topics


ESF_DETAIL = "/digitalni-nastroje/generator-importu-esf/"
OPZ_PAGE = "/digitalni-nastroje/nastroje-pro-opz/"


def build_esf_generator(email):
    return f'''<div class="system-page esf-page">
<section class="system-hero"><div class="wrap"><div class="breadcrumbs"><a href="/">Úvod</a> / <a href="{OPZ_PAGE}">Nástroje pro OPZ+</a> / Generátor importů</div><span class="eyebrow">Generátor importů do IS ESF 21+</span><h1>Z Excelu do IS ESF<br><em>bez ručního skládání CSV.</em></h1><p class="system-lead">Hromadný import podpořených osob a podpor bez ručního přepisování.</p><p>Připravte data v Excelu. Aplikace je zkontroluje, převede do požadované struktury a vytvoří soubor pro hromadný import do IS ESF 21+.</p><div class="contact-actions"><a class="button dark" href="{enquiry(email, 'Zájem o ukázku generátoru importů IS ESF 21+')}">Domluvit ukázku <span aria-hidden="true">→</span></a><a class="button contact-email" href="{OPZ_PAGE}">Další nástroje pro OPZ+</a></div><nav class="digital-jumps" aria-label="Možnosti generátoru"><a href="#podporene-osoby">Podpořené osoby</a><a href="#kontrola-adres">Kontrola adres</a><a href="#klientske-podpory">Klientské podpory</a><a href="#kontrola-exportu">Kontrola a export</a><a href="#zpracovani-udaju">Osobní údaje</a></nav></div></section>
<section class="section system-section" id="podporene-osoby"><div class="wrap system-split"><div><span class="eyebrow">XLSX → PodporeneOsoby.csv</span><h2>Podpořené osoby</h2><p>Nahrajte XLSX s klientskými údaji. Aplikace automaticky rozpozná běžné názvy sloupců; jejich přiřazení můžete zkontrolovat a upravit.</p><p>Výsledný soubor <code>PodporeneOsoby.csv</code> obsahuje všech 32 výstupních polí. Hotové CSV následně nahrajete do IS ESF 21+.</p></div><div class="esf-checklist"><h3>Co se kontroluje před exportem</h3><ul><li>Povinné údaje a formát dat</li><li>PSČ a telefonní čísla</li><li>Kódy pohlaví</li><li>Postavení na trhu práce</li><li>Dosažené vzdělání a znevýhodnění</li><li>Situace po ukončení účasti</li><li>Duplicity osob</li></ul></div></div></section>
<section class="section system-section system-wash" id="kontrola-adres"><div class="wrap system-split"><div><h2>Kontrola adres podle RÚIAN</h2><p>Adresní údaje lze zkontrolovat proti oficiálním datům Registru územní identifikace, adres a nemovitostí.</p><p>Po načtení klientského XLSX vyberete také soubor CSV nebo ZIP adresních míst stažený od ČÚZK. Kontrola probíhá nad těmito načtenými daty přímo v prohlížeči.</p></div><div><ul class="esf-list"><li>Existence obce v načtených datech</li><li>Existence čísla popisného v obci</li><li>Shoda PSČ s obcí</li><li>Vazba ulice na konkrétní číslo popisné</li></ul><p>Pokud je problém pouze v názvu ulice, lze její hodnotu vynechat pro následné dohledání v IS ESF nebo si nechat nabídnout odpovídající ulice z RÚIAN.</p></div></div></section>
<section class="section system-section" id="klientske-podpory"><div class="wrap system-split"><div><span class="eyebrow">Export osob + XLSX podpor → Podpory.csv</span><h2>Klientské podpory</h2><p>Načtěte aktuální export osob z IS ESF a XLSX s novými podporami. Aplikace spáruje podporu s konkrétním klientem a připraví <code>Podpory.csv</code> se 17 poli.</p><p>Pro porovnání s dříve evidovanými podporami lze navíc načíst historii. Přesnost této kontroly závisí na tom, zda historický soubor obsahuje potřebné údaje.</p></div><div class="esf-checklist"><h3>Co se kontroluje</h3><ul><li>Platný kód podpory</li><li>Rozsah prezenční a elektronické podpory</li><li>Data poskytování podpory</li><li>Jednoznačná identifikace klienta</li><li>Duplicity v právě importovaných datech</li><li>Shoda s podporami z načtené historie</li></ul></div></div></section>
<section class="section system-section system-wash" id="kontrola-exportu"><div class="wrap system-split"><div><h2>Chyby ještě před importem</h2><p>Každý řádek je před vytvořením výsledného souboru označen jako validní nebo chybný. U chybného záznamu aplikace vysvětlí, co je potřeba opravit.</p><p>Do výsledného CSV se zahrnou pouze validní záznamy.</p></div><div><h2>Kontrolní XLSX</h2><p>Vedle importního CSV lze stáhnout také kontrolní Excel. Obsahuje zpracované údaje společně s informacemi o nalezených chybách a varováních.</p><p>Před importem do IS ESF tak můžete výsledná data ještě jednou zkontrolovat.</p></div></div></section>
<section class="section system-section" id="zpracovani-udaju"><div class="wrap system-split"><div><span class="eyebrow">Zpracování v prohlížeči</span><h2>Nahrané údaje zůstávají ve vašem počítači.</h2></div><div><p>Aplikace nemá backend. Nahrané soubory se neposílají na server a osobní údaje se neukládají do LocalStorage ani jiného trvalého úložiště aplikace v prohlížeči.</p><p>Po obnovení stránky je proto potřeba soubory načíst znovu. Stažené CSV a kontrolní XLSX zůstávají tam, kam je sami uložíte.</p></div></div></section>
<section class="digital-custom system-tailored"><div class="wrap"><span class="eyebrow">Pro projekty OPZ+</span><h2>Méně přepisování.<br>Méně chyb při importu.</h2><p>Nástroj pro organizace, které do IS ESF 21+ zapisují větší množství podpořených osob nebo klientských podpor a nechtějí údaje zadávat jednotlivě.</p><div class="contact-actions"><a class="button" href="{enquiry(email, 'Zájem o ukázku generátoru importů IS ESF 21+')}">Domluvit ukázku <span aria-hidden="true">→</span></a><a class="digital-contact-link" href="{OPZ_PAGE}">Další nástroje pro OPZ+</a></div><a class="nno-back" href="/digitalni-nastroje/">← Všechny digitální nástroje</a></div></section></div>'''


def build_opz_tools(email):
    return f'''<div class="system-page opz-page"><section class="system-hero"><div class="wrap"><div class="breadcrumbs"><a href="/">Úvod</a> / <a href="/digitalni-nastroje/">Digitální nástroje</a> / Nástroje pro OPZ+</div><span class="eyebrow">Nástroje pro OPZ+</span><h1>Od importu dat<br><em>po vyhodnocení projektu.</em></h1><p class="system-lead">Tři nástroje pro opakující se práci při realizaci projektů.</p><p>Začněte tím, co právě potřebujete: připravit import do IS ESF, získat přehled o čerpání rozpočtu nebo propojit klientskou práci s řízením a evaluací projektu.</p><nav class="digital-jumps" aria-label="Vybrat nástroj pro OPZ+"><a href="#importy-esf">Importy do IS ESF</a><a href="#prehled-rozpoctu">Rozpočet OPZ+</a><a href="#evidence-a-evaluace">Evidence a evaluace</a></nav></div></section>
<section class="section system-section"><div class="wrap"><article class="esf-compact-offer" id="importy-esf"><div><span class="eyebrow">Malý praktický nástroj</span><h2>Generátor importů do IS ESF 21+</h2><p>Z Excelu do IS ESF bez ručního skládání CSV. Kontrola podpořených osob a podpor, adres a duplicit, importní CSV i kontrolní XLSX.</p></div><div class="esf-compact-actions"><a class="button dark" href="{enquiry(email, 'Zájem o ukázku generátoru importů IS ESF 21+')}">Domluvit ukázku →</a><a class="digital-enquiry" href="{ESF_DETAIL}">Jak generátor funguje →</a></div></article>
<div class="opz-products"><article id="prehled-rozpoctu"><span class="eyebrow">Finance projektu</span><h2>Sledovač čerpání rozpočtu OPZ+</h2><p>Skutečně schválené čerpání, zůstatky, paušální nárok a podklady pro přesuny prostředků v jednom přehledu.</p><p>Pracuje s exportem rozpočtu XLSX a PDF žádostí o platbu.</p><a class="button dark" href="/digitalni-nastroje/#rozpocet-opz">Prohlédnout Sledovač OPZ+ →</a></article><article id="evidence-a-evaluace"><span class="eyebrow">Klientská práce a výsledky</span><h2>Projektová evidence a evaluace pro NNO</h2><p>Cíle podpory, case management, projektové indikátory, pracovní výkazy, porady a evaluace v jedné navazující evidenci.</p><p>Od práce s klientem až po závěrečnou evaluační zprávu.</p><a class="button dark" href="/digitalni-nastroje/projektova-evidence-a-evaluace/">Prohlédnout možnosti systému →</a></article></div></div></section>
<section class="digital-custom system-tailored"><div class="wrap"><h2>Řešíte více oblastí najednou?</h2><p>Probereme, zda vám stačí samostatný nástroj, nebo potřebujete řešení přizpůsobené procesu a metodice vašeho projektu.</p><a class="button" href="{enquiry(email, 'Nástroje pro OPZ+ – potřeby našeho projektu')}">Probrat náš projekt →</a><br><a class="nno-back" href="/digitalni-nastroje/">← Všechny digitální nástroje</a></div></section></div>'''


BIO_DATA = [
    ("Identita a lokalita", ["Název společnosti, národní identifikátor, adresa, lokalita, právní forma a stav subjektu."]),
    ("Ekologická certifikace", ["Certifikace, kontrolní organizace, činnosti, zaměření a produkty."]),
    ("Kontakty a provozovny", ["Web, e-mail, telefon a informace o provozovnách."]),
    ("Ekonomické souvislosti", ["Podle dostupných zdrojů také finanční údaje, právní a ekonomický stav a informace související s insolvencí nebo likvidací."]),
]


def build_bio_registry(email):
    info = enquiry(email, "Informace o BIO Registry")
    demo = enquiry(email, "Žádost o ukázku – BIO Registry")
    return f'''<div class="system-page bio-page"><section class="system-hero"><div class="wrap"><div class="breadcrumbs"><a href="/">Úvod</a> / <a href="/digitalni-nastroje/">Digitální nástroje</a> / BIO Registry</div><span class="eyebrow">BIO Registry · desktopová aplikace pro Windows</span><h1>Bio firmy napříč Evropou<br><em>v jedné databázi.</em></h1><p class="system-lead">Registry, certifikace a obchodní kontakty bez procházení desítek různých zdrojů.</p><p>Informace o ekologických výrobcích, zpracovatelích, obchodnících a dalších certifikovaných subjektech jsou v jednotlivých zemích zveřejňovány různým způsobem. Někde existuje národní registr, jinde TRACES, otevřená data nebo databáze kontrolních organizací.</p><p>BIO Registry tato data sjednocuje do jednoho prostředí.</p><div class="contact-actions"><a class="button dark" href="{info}">Zjistit více o BIO Registry →</a><a class="button contact-email" href="{demo}">Chci ukázku</a></div><nav class="digital-jumps" aria-label="Možnosti BIO Registry"><a href="#zdroje-a-firmy">Zdroje a karta firmy</a><a href="#dohledavani-kontaktu">Dohledávání kontaktů</a><a href="#aktualizace-dat">Aktualizace</a><a href="#filtry-a-export">Filtry a export</a><a href="#pro-koho">Pro koho je nástroj</a></nav></div></section>
<section class="section system-section" id="zdroje-a-firmy"><div class="wrap"><div class="system-split"><div><h2>Jeden pohled na desítky národních zdrojů</h2></div><div><p>Aplikace pracuje s registry a veřejnými zdroji přibližně 30 zemí. Převádí je do společné struktury, díky které lze firmy vyhledávat a porovnávat bez ohledu na podobu původní databáze.</p><p>Součástí jsou například údaje z Česka, Slovenska, Německa, Rakouska, Francie, Itálie, Polska, Španělska, skandinávských zemí, Beneluxu a dalších evropských států.</p></div></div><div class="bio-company"><h2>Karta firmy</h2><p>Rozsah údajů se liší podle země a dostupných veřejných zdrojů. U jednotlivých subjektů lze podle dostupnosti zobrazit:</p><div class="system-topics">{topics(BIO_DATA)}</div></div></div></section>
<section class="section system-section system-wash" id="dohledavani-kontaktu"><div class="wrap system-split"><div><h2>Automatické dohledávání kontaktů</h2><p>Oficiální registry často obsahují informace o certifikaci, ale neobsahují použitelný obchodní kontakt. BIO Registry proto umí dohledávat další veřejně dostupné údaje: firemní web, e-mail, telefon nebo národní identifikátor.</p><p>Nalezený web nebo kontakt není přijat pouze podle podobnosti názvu. Aplikace pracuje také s adresou, PSČ, národním identifikátorem nebo údaji zveřejněnými přímo na webu firmy.</p></div><div><h2>Kontakty s dohledatelným původem</h2><p>U kontaktu je možné evidovat jeho zdroj, způsob přiřazení, jistotu shody a datum ověření.</p><p>Pokud nový zdroj nalezne jiný e-mail nebo telefon, nemusí automaticky přepsat dosavadní hodnotu. Rozdílné údaje mohou být předloženy ke kontrole společně s podklady, podle kterých byly nalezeny.</p></div></div></section>
<section class="section system-section"><div class="wrap system-split"><div><h2>Automatická kontrola pomocí AI</h2></div><div><p>Sporné kontakty lze dále automaticky posuzovat. Aplikace nejprve ověřuje, že navržený kontakt skutečně existuje na veřejném zdroji, a následně kontroluje, zda důkazy odpovídají konkrétní firmě.</p><p>Automaticky lze přijmout pouze výsledek s dostatečně silným důkazem identity a vysokou mírou jistoty. Nejednoznačné případy zůstávají pracovníkovi ke kontrole.</p></div></div></section>
<section class="section system-section system-wash" id="aktualizace-dat"><div class="wrap system-split"><div><h2>Databáze, která se průběžně aktualizuje</h2><p>Jednotlivé země mají vlastní aktualizační postupy a mohou být pravidelně zpracovávány na pozadí. Pokud je některý zdroj dočasně nedostupný, další země mohou pokračovat ve zpracování.</p></div><div class="esf-checklist"><h3>Přehled o zpracování</h3><ul><li>Plánované aktualizace a běžící úlohy</li><li>Fronta dalších zemí</li><li>Chyby zdrojů</li><li>Historie dokončených běhů</li><li>Stáří použitých dat</li><li>Nové nebo doplněné kontaktní údaje</li></ul></div></div></section>
<section class="section system-section" id="filtry-a-export"><div class="wrap system-split"><div><h2>Vyhledávání a filtry</h2><p>Databázi lze filtrovat podle země, kontrolní organizace, typu operátora, činnosti nebo dalších údajů dostupných v konkrétním registru.</p><p>Obchodní výběr tak lze vytvořit v jednom prostředí.</p></div><div><h2>Export pro další práci</h2><p>Vybranou část databáze lze exportovat do XLSX nebo CSV. Uživatel si může zvolit aktuálně filtrované firmy, celý dostupný seznam i konkrétní sloupce.</p><p>Výsledná data lze použít pro obchodní analýzu, další zpracování nebo práci v CRM.</p></div></div></section>
<section class="section system-section system-wash"><div class="wrap system-split"><div><span class="eyebrow">Desktopová aplikace pro Windows</span><h2>Pracovní databáze u vás v počítači</h2></div><div><p>Pracovní databáze BIO Registry se ukládá lokálně do počítače uživatele. Také přístupové klíče k volitelným službám jsou ukládány lokálně a šifrovaně.</p><p>Dohledávání veřejných údajů a použití volitelných online služeb vyžaduje připojení k internetu.</p></div></div></section>
<section class="section system-section" id="pro-koho"><div class="wrap"><h2>Pro koho může být BIO Registry užitečný?</h2><p>Pro firmy a organizace, které potřebují systematicky pracovat s evropským bio trhem.</p><ul class="bio-audiences"><li>Výrobci hledající nové odběratele</li><li>Distributoři a velkoobchody</li><li>Exportní oddělení</li><li>Nákupčí hledající nové dodavatele</li><li>Poradenské a obchodní společnosti</li><li>Organizace analyzující ekologický sektor</li></ul></div></section>
<section class="digital-custom system-tailored"><div class="wrap"><h2>Místo desítek registrů<br>jedna pracovní databáze.</h2><p>Probereme, jaké země, typy firem a údaje potřebujete pro svou práci.</p><div class="contact-actions"><a class="button" href="{info}">Zjistit více o BIO Registry →</a><a class="digital-contact-link" href="{demo}">Chci ukázku</a></div><a class="nno-back" href="/digitalni-nastroje/">← Všechny digitální nástroje</a></div></section></div>'''
